services:
  api:
    build: .
    container_name: face_rec_api
    ports:
      - "5000:5000"
    volumes:
      # host_path:container_path
      # - ./uploads:/app/uploads
      # - ./facial_rec.db:/app/facial_rec.db
      - .:/app
